### PR TITLE
Add statistics

### PR DESCRIPTION
**Pull request by monsieurhannes**

### CODE REVIEW

**Comment by qerub** [comment]
I think the first one is great but the second feels a bit too large to have on the landing page. Can we put in one a page dedicated to statistics / history maybe?

**Comment by monsieurhannes** [comment]
Oh, just saw your comment :D 
What do you think now?

**Comment by qerub** [comment]
I still think the same, but I won't stop you from hitting the merge button.

**Comment by monsieurhannes** [comment]
Is it possible to force the content of an iframe to fit the boundary?

**Pull request merged**
