### PR TITLE
Switch to Sleek theme

### PR DESCRIPTION
**Pull request by qerub**

### CODE REVIEW

**Comment by qerub** [comment]
@monsieurhannes: Feel free to continue from here if you like.

**Comment by monsieurhannes** [comment]
Duplicate of #21

**Comment by monsieurhannes** [comment]
It looks great! I would say we merge it right away and work on the content in the background?

**Comment by qerub** [comment]
> It looks great! I would say we merge it right away and work on the content in the background?

No, I think we should make the Sleek-based site (at least) as functional as the current before merging (e.g. `blog.html` needs to be rewritten).

**Comment by qerub** [comment]
Left to do:
- [ ] Replace text/logo in header
- [ ] Add link to feed (preferably with a recognisable icon)
- [ ] Add link to Facebook page

**Comment by monsieurhannes** [comment]
Insta-logo is visible on my machine!

**Comment by qerub** [comment]
> Insta-logo is visible on my machine! There is no facebook button though.

Turns out it was my adblocker! :)

**Comment by qerub** [comment]
> […] There is no facebook button though.

Sleek has no built-in Facebook button.

**Comment by monsieurhannes** [comment]
>     * [ ]  Add link to feed (preferably with a recognisable icon)

What do you mean with that?

**Comment by monsieurhannes** [comment]
> 
> 
> > […] There is no facebook button though.
> 
> Sleek has no built-in Facebook button.

We could have an CC Email-Button as well (maybe)?

**Comment by qerub** [comment]
@monsieurhannes: What do you think about adding buttons for emailing and the feed next to the social media buttons? Is that good enough? (#7 is still interesting.)

**Comment by monsieurhannes** [comment]
Exactly what I thought of! Even though I don't think that the feed will get used.

**Pull request merged**
